CREATE TABLE WEATHER_LOG
(
   ID INTEGER NOT NULL AUTO_INCREMENT,
   RESPONSE_ID VARCHAR(255) NOT NULL,
   LOCATION VARCHAR(255) NOT NULL,
   ACTUAL_WEATHER VARCHAR(255) NOT NULL,
   TEMPERATURE VARCHAR(255) NOT NULL,
);